language: java

before_install:
  - export TERM=dumb
  # we need the following because of https://github.com/JakeWharton/sdk-manager-plugin/issues/13
  - sudo apt-get update -qq
  - sudo apt-get install -qq libstdc++6:i386 lib32z1 expect

install:
  - ./gradlew clean build

notifications:
  email: false